plexinc-plugins/Services.bundle

- Contents/Service Sets/com.plexapp.plugins.newsy/URL/Newsy/ServiceCode.pys
https://forums.plex.tv/index.php/topic/140575-newsy-plugin/
> Newsy: Fix for updated website

- Contents/Service Sets/com.plexapp.plugins.logotv/ServiceInfo.plist
- Contents/Service Sets/com.plexapp.plugins.logotv/URL/Logo TV/ServiceCode.pys
Added new URL pattern for new show formats
> LogoTV Update ServiceInfo plist

- Contents/Service Sets/com.plexapp.plugins.spike/URL/Spike/ServiceCode.pys
Updated the Metadata and mgid pulls for new page format
> Spike URL service fix

- Contents/Service Sets/com.plexapp.plugins.fox/ServiceInfo.plist
- Contents/Service Sets/com.plexapp.plugins.fox/URL/FOX/ServiceCode.pys
See comment in PlayVideo routine
> FOX: New URL Service

- Contents/Service Sets/com.plexapp.plugins.hgtvcanada/URL/HGTV Canada/ServiceCode.pys
> Updated HGTV Canada

- Contents/Service Sets/com.plexapp.plugins.mtv/ServiceInfo.plist
- Contents/Service Sets/com.plexapp.plugins.mtv/URL/MTV/ServiceCode.pys
Cleaned up URL service. Also added a shorter id to the URL pattern. And added a duration to the Metadata because the new Roku app will not play parts properly without it.
> MTV URL Service Fix

- Contents/Service Sets/com.plexapp.plugins.hgtvcanada/URL/HGTV Canada/ServiceCode.pys
Fix for issue filed here:
https://github.com/plexinc/plex-media-player/issues/1#issuecomment-149648603
> Incorrect Bitrate

- Contents/Service Sets/com.plexapp.plugins.cnettv/URL/CNET/ServiceCode.pys
Fixed an error in the code due to a change with the code of the webpages for CNET
> CNET json error fix

- Contents/Service Sets/com.plexapp.plugins.lstudio/ServiceInfo.plist
- Contents/Service Sets/com.plexapp.plugins.lstudio/URL/L Studio/ServiceCode.pys
The L studio website has completely redone their website. All the videos available on their website now access YouTube videos
> L Studio URL service rewrite

- Contents/Service Sets/com.plexapp.plugins.abc/URL/ABC/ServiceCode.pys
This fixes a metadata issue due to some video urls using @name and some
using @property
> Metadata Fix

- Contents/Service Sets/com.plexapp.plugins.pftv/URL/vidzi.tv/ServiceCode.pys
Added mp4 and hls support.  The hls worked for me, but was only tested with Android and Chromecast.  Vidzi.tv seems to not use _p.a.c.k.e.r_ anymore, hence it's removal from the code.
> fixed vidzi.tv

- Contents/Service Sets/com.plexapp.plugins.pftv/URL/vidzi.tv/ServiceCode.pys
Seems like over the past few weeks vidzi.tv has undergone some maintenance.  Now they have reverted back to p.a.c.k.e.r format.  I've just reverted the code back to the original.
> vidzi.tv reverted back to p.a.c.k.e.r format

- Contents/Service Sets/com.plexapp.plugins.mtv/ServiceInfo.plist
- Contents/Service Sets/com.plexapp.plugins.mtv/URL/MTV/ServiceCode.pys
Update URL pattern and vevo regex as well as replaced vevo code that I
wrongly removed. Could find no hive videos, so deleting those from the pattern
> Update URL pattern and vevo

- Contents/Service Sets/com.plexapp.plugins.drdk/URL/drdk/ServiceCode.pys
DR changed API version to 1.3...SIGH...
Thanks to community member ricki@erikXXXX.dk for this info
> drdk changed api version to 1.3

- Contents/Service Sets/com.plexapp.plugins.aetv/URL/AETV/ServiceCode.pys
Reverted back to previous signature code. New code is not working.
> A&E - revert to previous signature code

- Contents/Service Sets/com.plexapp.plugins.lifetime/URL/Lifetime/ServiceCode.pys
Reverted back to old signature method
> Lifetime - Revert to old signature method

- Contents/Service Sets/com.plexapp.plugins.cnn/ServiceInfo.plist
- Contents/Service Sets/com.plexapp.plugins.cnn/URL/CNN/ServiceCode.pys
This URL service will work with videos from the website and pulls the XML data for each and gets the MP4s. The XML also includes HLS format videos, but since some clients have issues with HLS, decided to go with MP4 options only.
> CNN - New URL service

- Contents/Service Sets/com.plexapp.plugins.lifetime/URL/Lifetime/ServiceCode.pys
Changed media object to HLS since all videos are HLS format now.
Currently being transcoded by all clients.
> Lifetime - Change to HLS

- Contents/Service Sets/com.plexapp.plugins.aetv/URL/AETV/ServiceCode.pys
Changed media object to HLS since all videos are HLS format now. Currently being transcoded by all clients.
> AETV - Change to HLS

- Contents/Service Sets/com.plexapp.plugins.historychannel/URL/History Channel/ServiceCode.pys
Updated the URL service to use the A&E signature method and changed media object to HLS
> History Channel - New URL service

- Contents/Service Sets/com.plexapp.plugins.nationalgeographic/URL/National Geographic/ServiceCode.pys
> NatGeo - update video service

- Contents/Service Sets/com.plexapp.plugins.internetarchive/URL/Internet Archive/ServiceCode.pys
Not supported by Framework anymore?
> IA: Remove directors from EO to fix video playback

- Contents/Service Sets/com.plexapp.plugins.cmt/ServiceInfo.plist
- Contents/Service Sets/com.plexapp.plugins.cmt/URL/CMT/ServiceCode.pys
- Contents/Service Sets/com.plexapp.plugins.mtv/ServiceInfo.plist
- Contents/Service Sets/com.plexapp.plugins.mtv/URL/MTV/ServiceCode.pys
Added a separate URL service for CMT since it still uses RTMP and has old web code. Then rewrote URL service to pull HLS videos.
> MTV - Rewrite to use HLS and create separate CMT URL service

- Contents/Service Sets/com.plexapp.plugins.logotv/URL/Logo TV/ServiceCode.pys
Rewrote URL service to pull HLS videos instead of RTMP
> LogoTV - Rewrite for HLS

- Contents/Service Sets/com.plexapp.plugins.southpark/URL/South Park/ServiceCode.pys
New URL service that fixes issue with parts and uses HLS streams instead of RTMP.
> Soutpark - Update to use HLS

- Contents/Service Sets/com.plexapp.plugins.viasat/ServiceInfo.plist
- Contents/Service Sets/com.plexapp.plugins.viasat/URL/Viasat Play/ServiceCode.pys
https://forums.plex.tv/discussion/comment/1255321/#Comment_1255321
> Viasat Play: Fix broken service

- Contents/Service Sets/com.plexapp.plugins.tvland/ServiceInfo.plist
- Contents/Service Sets/com.plexapp.plugins.tvland/URL/TVLand/ServiceCode.pys
TV Land has updated its website to use the new methods and new URL patterns for Viacom Networks. Updated URL pattern and updated ServiceCode to pull HLS streams like other Viacom network websites.
> TVLand - Update URL service

- Contents/Service Sets/com.plexapp.plugins.schweizerfernsehen/ServiceInfo.plist
- Contents/Service Sets/com.plexapp.plugins.schweizerfernsehen/URL/Schweizer Fernsehen/ServiceCode.pys
Use the new website to fetch all podcasts. Needs Schweizer-Fernsehen.bundle pull request, too.
> Handle the new website

- Contents/Service Sets/com.plexapp.plugins.xxx/URL/RedTube/ServiceCode.pys
Now they also changed the video_url...
> Fixed video_url

- Contents/Service Sets/com.plexapp.plugins.mtv/URL/MTV/ServiceCode.pys
Like other Viacom websites they have removed the mgid from the HTML pages. so we use the manifest to pull the video id number.
> MTV - Update MGID pull

- Contents/Service Sets/com.plexapp.plugins.comedycentral/ServiceInfo.plist
change need to match change in  comedycentral.bundle
> Update comedy central ServiceInfo.plist

- Contents/Service Sets/com.plexapp.plugins.spike/URL/Spike/ServiceCode.pys
Updated code for updates to website. The current URL service no longer works due to no video player mgid code on page.
> Spike - Updated code

- Contents/Service Sets/com.plexapp.plugins.mtv/ServiceInfo.plist
Update URL pattern for more consistency with other Viacom URL services
> MTV - Update URL pattern

- Contents/Service Sets/com.plexapp.plugins.xxx/ServiceInfo.plist
- Contents/Service Sets/com.plexapp.plugins.xxx/URL/RedTube/ServiceCode.pys
As communicated via media PornHub & Co now use HTTPS.
> RedTube now uses HTTPS

- Contents/Service Sets/com.plexapp.plugins.mtv/ServiceInfo.plist
- Contents/Service Sets/com.plexapp.plugins.mtv/URL/MTV/ServiceCode.pys
Add support for video playlists
> MTV - Add support for video playlist

- Contents/Service Sets/com.plexapp.plugins.comedycentral/URL/Comedy Central/ServiceCode.pys
Added additional code to pull URI from Manifest for URLs that do not have the ccnetapp code
> Comedy Central - Add additional URI pull

- Contents/Service Sets/com.plexapp.plugins.lifetime/ServiceInfo.plist
- Contents/Service Sets/com.plexapp.plugins.lifetime/URL/Lifetime/ServiceCode.pys
Lifetime now uses multi-quality m3u8s and pull smil from different xpath. Also updated movie/specials URL pattern
> Lifetime - Update URL service

- Contents/Service Sets/com.plexapp.plugins.svtplay/URL/SVTPlay/ServiceCode.pys
https://forums.plex.tv/discussion/comment/1464761/#Comment_1464761
> SVTPlay: Change API URL for video info to fix broken service

- Contents/Service Sets/com.plexapp.plugins.svtplay/URL/SVTPlay/ServiceCode.pys
Hi,
These two commits address found issues with SVTPlay.
First related to images not are displayed and the second addresses that some shows are not using 'A' for the video id.
> Corrections to SVTPlay

- Contents/Service Sets/com.plexapp.plugins.mtv/URL/MTV/ServiceCode.pys
Change b value to reorder multi-resolution m3u8s offered by the websites
> MTV - Change b value

- Contents/Service Sets/com.plexapp.plugins.spike/URL/Spike/ServiceCode.pys
Added alternate _b_ code to reorder media
> Spike - add b code

- Contents/Service Sets/com.plexapp.plugins.teamcoco/ServiceInfo.plist
Include comicom videos in URL pattern
> Team Coco - Update URL pattern

- Contents/Service Sets/com.plexapp.plugins.lifetime/ServiceInfo.plist
- Contents/Service Sets/com.plexapp.plugins.lifetime/URL/Lifetime/ServiceCode.pys
Update URL pattern to accept seasons that are four digits and represent a year
> Lifetime - Update URL pattern for year seasons

- Contents/Service Sets/com.plexapp.plugins.aetv/ServiceInfo.plist
- Contents/Service Sets/com.plexapp.plugins.aetv/URL/AETV/ServiceCode.pys
Updated URL service to use same format as Lifetime due to changes in the website for the location of the smil and only offers one resolution option now
> A&E - Updated url service

- Contents/Service Sets/com.plexapp.plugins.historychannel/ServiceInfo.plist
- Contents/Service Sets/com.plexapp.plugins.historychannel/URL/History Channel/ServiceCode.pys
Update URL service to use Lifetime URL service code.
> History - Update URL service

- Contents/Service Sets/com.plexapp.plugins.southpark/URL/South Park/ServiceCode.pys
Pull media part URL from json to ensure the language is correct. Also remove bitrate reference since pulling one multi-quality m3u8 do not need is and if bitrates vary it splits the video into multiple media objects
> South Park - Fix language and bitrate issue

- Contents/Service Sets/com.plexapp.plugins.comedycentral/URL/Comedy Central/ServiceCode.pys
Pull media part URL from json to ensure the language is correct. Also remove bitrate reference since pulling one multi-quality m3u8 do not need is and if bitrates vary it splits the video into multiple media objects
> Comedy Central - Fix language and bitrate issue

- Contents/Service Sets/com.plexapp.plugins.nbc/ServiceInfo.plist
- Contents/Service Sets/com.plexapp.plugins.nbc/URL/NBC/ServiceCode.pys
Updated URL service for new code
> NBC - Rewrite of URL service

- Contents/Service Sets/com.plexapp.plugins.nbc/URL/NBC/ServiceCode.pys
Add video resolution to NBC URL service.
> NBC - Add video resolution

- Contents/Service Sets/com.plexapp.plugins.tvland/URL/TVLand/ServiceCode.pys
Updated manifest pull because there were issues pulling manifest with some shows.
Fixes issue with Teachers
> TVLAND - Update Manifest pull

- Contents/Service Sets/com.plexapp.plugins.paramount/ServiceInfo.plist
- Contents/Service Sets/com.plexapp.plugins.paramount/URL/Paramount/ServiceCode.pys
Add new URL service for Paramount Network (formerly Spike)
> Paramount -  Add URL service

- Contents/Service Sets/com.plexapp.plugins.paramount/URL/Paramount/ServiceCode.pys
Updated mgid pull for new website design
> Paramount -Update mgid pull
