- Contents/Service Sets/com.plexapp.plugins.iplayer/ServiceInfo.plist
- Contents/Service Sets/com.plexapp.plugins.iplayer/URL/BBC iPlayer/ServiceCode.pys
The HLS streams are stable but only available in 468p
- May work as a temporary solution until the problem with RTMP is fixed?
> BBC iPlayer: Use HLS instead of RTMP

- Contents/Service Sets/com.plexapp.plugins.logotv/ServiceInfo.plist
- Contents/Service Sets/com.plexapp.plugins.logotv/URL/Logo TV/ServiceCode.pys
Added plural version of video and 5 digit option to URL pattern. Rewrote MetadataforURL to include duration, so it will be work with the new Roku Preview app. Updated uri pull to ensure video playlist pull. And cleaned up code to make it more uniform with other Viacom URL services.
> LogoTV - Fixed duration, playlist pull, and URL pattern

- Contents/Service Sets/com.plexapp.plugins.svtplay/URL/SVTPlay/ServiceCode.pys
Since the introduction of the SSL features in PMS, the patch for PHT is not working anymore(in a reliable way) since you have to 'Disable Secure Connections' in order for it to work.
This update will make PHT be able to play VOD programs independent of PMS secure connection setting, e.g. you can now set 'Required'. 
An update for the new Apple TV is also included so that client will get access to the master playlist(which enables subtitles etc)
> SVT Play: Fix for PHT + new Apple TV

- Contents/Service Sets/com.plexapp.plugins.fox/URL/FOX/ServiceCode.pys
Seems like the akamai domain finally got a valid SSL certificate ... 
We still need to keep the alternative for clients like PHT(no SSL support).
> FOX: SSL certificate now valid -> Let compatible clients get access to original url

- Contents/Service Sets/com.plexapp.plugins.abcfamily/URL/ABC Family/ServiceCode.pys
Fix thumb error in MetadataforURL function due to a page not having a thumb. Added an except that pulls a default logo image.
> Fix thumb error

- Contents/Service Sets/com.plexapp.plugins.iplayer/URL/BBC iPlayer/ServiceCode.pys
This will help clients to better choose the correct source resolution, i.e. if omitting the bitrate PMS will always choose the max bitrate resolution when transcoding. Without this update it will lead to buffering if the bandwidth is not sufficient on the PMS computer: https://forums.plex.tv/discussion/198650/iplayer-streaming#latest
> Add bitrates to mediaobject + add framerate

- Contents/Service Sets/com.plexapp.plugins.vimeo/URL/Vimeo/ServiceCode.pys
The Vimeo URL service was returning a Media Not Available error because the xml for pulling the config url no longer works. 
Now the config url is listed two places in scripts of the web page, so have to use regex. Easiest pull is from a "window.vimeo.clip_page_config" area of json. So changed it to be pulled with regex and json from the data of the page
> Vimeo - Fix error pulling config url

- Contents/Service Sets/com.plexapp.plugins.aetv/ServiceInfo.plist
- Contents/Service Sets/com.plexapp.plugins.aetv/URL/AETV/ServiceCode.pys
They changed the coding in their website so the smil was different.
They seem to be in the process of changing the website and some URLs. So the URL given on the list of full episodes or clips in the video section will often be wrong but will redirect to a valid page, so if you keep the redirect=false in the code, the videos will fail. 
I set up the smil url to have the SMIL_DETAILS added to the end of the url. I tried just adding the ?format=SMIL to the end, but some videos would play while others failed.
> A&E - Fixed smil pull

- Contents/Service Sets/com.plexapp.plugins.logotv/URL/Logo TV/ServiceCode.pys
Set media object attributes directly on the object and Add video_codec and audio_codec to MediaObject to match other Viacom websites
> LogoTV - Media attribute fix

- Contents/Service Sets/com.plexapp.plugins.tvland/URL/TVLand/ServiceCode.pys
Set media object attributes directly on the object and Add video_codec and audio_codec to MediaObject to match other Viacom channels
> TV Land - Add media objects

- Contents/Service Sets/com.plexapp.plugins.cnn/URL/CNN/ServiceCode.pys
Fixed issue with some videos that do not work with the 3.0 version XML. Added HLS for these videos.
Found some cnn money videos that did not work with the existing XML variable format. Those videos used a completely different XML layout and only offered a few very low quality mp4 options, so I added the HLS for those instead.
> CNN - Fix video issue

- Contents/Service Sets/com.plexapp.plugins.historychannel/ServiceInfo.plist
Add URL pattern for website URLs. The URLs used by the channel will actually redirect to the season/episode URL that is used by the website
> History - Add URL pattern

- Contents/Service Sets/com.plexapp.plugins.lifetime/ServiceInfo.plist
Add URL pattern for website URLs. The URLs used by the channel will actually redirect to the season/episode URL that is used by the website
> Lifetime - Add URL pattern

- Contents/Service Sets/com.plexapp.plugins.dplay/URL/Dplay/ServiceCode.pys
I believe that PMS v1.0 actually tries to handle the streams as HEVC -> the fix for incompatible clients doesn't work anymore.
Work around this by returning the content of the master playlist, this will make Plex/Web clients and PHT to be able to play the videos
> DPlay: Update fix for webclients + PHT

- Contents/Service Sets/com.plexapp.plugins.twitchtv/URL/Twitch.tv/ServiceCode.pys
Twitch.tv now returns HTTP error 400 for API calls without a client id. 
Registered application with Twitch as "Plex-plugin: Twitch.Tv".
Added client id to HTTP headers in Twitch.tv plugin ServiceCode.pys.
> Added twitch api client id to HTTP headers

- Contents/Service Sets/com.plexapp.plugins.southpark/URL/South Park/ServiceCode.pys
Some Plex player apps will not play all parts if they follow a very short part, so until the Plex player apps update their code, this will allow users to skip the short flash screen at the beginning that causes
parts not to play.
This should be addressed and fixed by each of the Plex player apps, but adding this exception will allow users to watch older Southpark videos until the apps resolve the issue.
> South Park - Fix short parts issue

- Contents/Service Sets/com.plexapp.plugins.googledrive/URL/Google Drive/ServiceCode.pys
Found the transcoding issue.  It seems the version of ffmpeg bundled with PMS has updated, and now requires the `path` and `domain` to be set for cookies (ffmpeg ref [HTTP-Cookies](https://www.ffmpeg.org/ffmpeg-protocols.html#HTTP-Cookies)).
> Google Drive - fixed cookies for ffmpeg update & added back audio_channels=2

- Contents/Service Sets/com.plexapp.plugins.cbcnewsnetwork/ServiceInfo.plist
- Contents/Service Sets/com.plexapp.plugins.cbcnewsnetwork/URL/CBC/ServiceCode.pys
- Contents/Service Sets/com.plexapp.plugins.cbcnewsnetwork/URL/CBCRadio/ServiceCode.pys
- Contents/Service Sets/com.plexapp.plugins.cbcnewsnetwork/URL/WatchCBC/ServiceCode.pys
CBC Radio moved to a new URL — and presumably to a new API — so this
required a rewrite. Many video categories also moved to a new video player; wrote a new URL
service for that.
I've had a few folks testing the changes on the [Plex forums](https://forums.plex.tv/discussion/225718/cbc-channel-issue#latest); there might be a few open issues but it would help to get more people/devices using it.
Existing URL service is not changed, other than a few comments to help
with dev/debugging. It's still in use for live sports and news. 
I'll have an updated channel as well.
> New URL Service for Radio and Watch.cbc.ca

- Contents/Service Sets/com.plexapp.plugins.googledrive/URL/Google Drive/ServiceCode.pys
While debugging another channel, I found out that the cookie domain name varies some, so added some regex code to pull out and use correct domain name in cookies.
> GoogleDrive - dynamic domain name in cookies

- Contents/Service Sets/com.plexapp.plugins.comedycentral/ServiceInfo.plist
Update URL pattern to include both URLs with "/episodes/" and "/full-episodes/" to accept full standup shows which still use the URLs with "/full-episodes/".
> Comedy Central - Update URL Pattern

- Contents/Service Sets/com.plexapp.plugins.mtv/URL/MTV/ServiceCode.pys
Fixed error as a result of the media URLs no longer including http:
> MTV - Fix media URL issue

- Contents/Service Sets/com.plexapp.plugins.spike/URL/Spike/ServiceCode.pys
Media URLs need http added to the beginning
> Spike - Fix media URLs

- Contents/Service Sets/com.plexapp.plugins.tv4play/URL/TV4 Play/ServiceCode.pys
- Don't use https since the cipher negotiation fails
- Prepare removal of login since Premium is not available anymore. The rest of the removal will be done at a later time to better sync it with the TV4Play.bundle(so that this change will hopefully be unnoticeable for the user)
> Tv4play fix for broken service

- Contents/Service Sets/com.plexapp.plugins.mtv/URL/MTV/ServiceCode.pys
- Contents/Service Sets/com.plexapp.plugins.spike/URL/Spike/ServiceCode.pys
Update code for media URLs. The websites removed the lead http: on the media URLs and now they are starting to replace it with https:
> Viacom - MTV and Spike Update

- Contents/Service Sets/com.plexapp.plugins.fox/URL/FOX/ServiceCode.pys
The code that pulled the individual resolutions for the multi-resolution m3u8s was causing playback from Watch Later to fail. This update removes that individual resolutions pull code and just provides the multi-resolution m3u8s.
When accessing the online version of this URL service from Watch Later, the players are not able to recognize the client specific code and always choose the alternative code for pulling the individual resolutions. Since playback fails from Watch Later on multiple clients (tested Plex Web, Roku, and iOS) this alternative code is not working. 
Since all official Plex players should be able to access multi-resolution m3u8s and other URL services use multi-resolution m3u8s (ex. Comedy Central). It is better to remove any alternative code.
Video playback was also …
> FOX - Removed Individual resolution pull

- Contents/Service Sets/com.plexapp.plugins.ted/ServiceInfo.plist
They changed from https to http in thier URLs and so the channel was failing. Added question mark to URL patttern to prevent this for any future changes.
> Ted Talks - update URL pattern

- Contents/Service Sets/com.plexapp.plugins.aetv/URL/AETV/ServiceCode.pys
- Contents/Service Sets/com.plexapp.plugins.historychannel/URL/History Channel/ServiceCode.pys
- Contents/Service Sets/com.plexapp.plugins.lifetime/URL/Lifetime/ServiceCode.pys
Add resolution for media objects for all A&E Network URL services (Lifetime, AETV, and History Channel)
> A&E Networks - Add resolution to media objects

- Contents/Service Sets/com.plexapp.plugins.liveleak/ServiceInfo.plist
Sometimes there are 4 instead of 5 characters before the underscore
> Liveleak: Fix in URL pattern to support all videos from plugin
